spring:
  config:
    import: file:./src/main/resources/.env[.properties]
  main:
    web-application-type: reactive
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: Portfolio
  data:
    r2dbc:
      repositories:
        enabled: true
    mongodb:
      uri: ${MONGODB_URI}
      host: ${MONGODB_HOST}
      repositories:
        type: reactive
      password: ${MONGODB_PASSWORD}
      username: ${MONGODB_USERNAME}
      authentication-database: admin
      auto-index-creation: true
      database: ${MONGODB_DATABASE}